/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 rock.gltf --transform
Author: violetaraffin (https://sketchfab.com/violetaraffin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-rock-illustrated-30bbdc39b6fe483aa29e887309fab100
Title: Low Poly Rock illustrated
*/

import { useGLTF } from "@react-three/drei";

export default function Rock(props) {
  const { nodes, materials } = useGLTF("/rock-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Rock4_low_Rock_0.geometry}
        material={materials.Rock}
      />
    </group>
  );
}

useGLTF.preload("/rock-transformed.glb");
